# .github/workflows/build-from-azdo.yml

name: Build from Azure DevOps Repo

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  # Variables from your Azure DevOps pipeline
  SOLUTION: '**/*.sln'
  BUILD_PLATFORM: 'Any CPU'
  BUILD_CONFIGURATION: 'Release'
  AZDO_ORG: 'punitsinc'
  AZDO_PROJECT: 'PartsUnlimited'
  AZDO_REPO: 'PartsUnlimited'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Clone Azure DevOps Repo
      run: |
        git clone https://${{ env.AZDO_ORG }}:${{ secrets.AZDO_PAT }}@dev.azure.com/${{ env.AZDO_ORG }}/${{ env.AZDO_PROJECT }}/_git/${{ env.AZDO_REPO }}
      shell: pwsh

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Set up NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Restore NuGet packages
      working-directory: ./${{ env.AZDO_REPO }}
      run: nuget restore ${{ env.SOLUTION }}

    - name: Build solution
      working-directory: ./${{ env.AZDO_REPO }}
      run: |
        msbuild.exe ${{ env.SOLUTION }} /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="${{ github.workspace }}/artifact" /p:Platform="${{ env.BUILD_PLATFORM }}" /p:Configuration="${{ env.BUILD_CONFIGURATION }}"

    - name: Copy JSON files to artifact directory
      working-directory: ./${{ env.AZDO_REPO }}
      run: Copy-Item -Path '**/*.json' -Destination '${{ github.workspace }}/artifact' -Recurse -Force
      shell: pwsh

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: drop
        path: ${{ github.workspace }}/artifact
